name: Sync posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 用系统提供的 token

      - name: Clone A repository (_posts)
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN }}@github.com/SSMemory/ssmemory.github.io.git repo-a

      - name: Replace _posts from A
        run: |
          rm -rf _posts
          mkdir -p _posts
          cp -r repo-a/_posts/* _posts/
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add _posts
          git commit -m "同步 _posts 从 SSMemory 仓库" || echo "无变更，无需提交"
          git push
