name: Sync posts from Repo A

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: '0 1 * * *'  # 每天凌晨 1 点自动同步（UTC）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout B repository
        uses: actions/checkout@v3

      - name: Clone A repository (_posts)
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.TOKEN }}@github.com/SSMemory/ssmemory.github.io.git repo-a

      - name: Replace _posts from A
        run: |
          rm -rf _posts
          mkdir -p _posts
          cp -r repo-a/_posts/* _posts/
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add _posts
          git commit -m "同步 _posts 从 SSMemory 仓库" || echo "无变更，无需提交"
          git push
